Feature/133
Khanhtran47/remix-movie pull request #137
Opened 2022-09-07 16:14 UTC by ctuanle

2022-09-07 19:38 UTC, Khanhtran47 commented
@ctuanle cái ni m đang lm tiếp à hay review luôn

2022-09-07 19:51 UTC, ctuanle commented
@Khanhtran47  t thấy style còn hơi phèn, định sửa lại chút thử xem 😅

2022-09-07 21:43 UTC, ctuanle commented
@Khanhtran47 có mấy đoạn như ri t k biết làm răng cho chuẩn cả :v 

![image](https://user-images.githubusercontent.com/70543626/188988121-dad9daab-52f4-46c0-87ab-e63612e52fea.png)

2022-09-07 22:27 UTC, Khanhtran47 requested changes
@ctuanle còn bên size Text chắc sau refactor code một lần rồi sửa luôn

2022-09-07 22:27 UTC, Khanhtran47 commented on app/src/components/media/item/RowItem.tsx
> +              IMDb
@ctuanle cái ni t nghĩ chắc phải fetch api mô chứa điểm imdb chứ điểm hiện tại vẫn là của tmdb nơi

2022-09-07 22:27 UTC, Khanhtran47 commented on app/src/components/media/item/RowItem.tsx
> +      gap={1}
@ctuanle t nghĩ ở đây cho khoảng cách giữa từng row to lên tý 
bên shadow cho dark mode thì chuyển màu sáng xám xám với giảm bottom shadow xuống tẹo

2022-09-07 22:27 UTC, Khanhtran47 commented on app/src/components/media/item/RowItem.tsx
> +      css={{
@ctuanle đây t nghĩ thêm maxWidth: '1400px' đồ rứa để giới hạn lại cho màn hình to k cái row nó dài quá

2022-09-07 22:30 UTC, Khanhtran47 commented
> @Khanhtran47 có mấy đoạn như ri t k biết làm răng cho chuẩn cả :v
> 
> ![image](https://user-images.githubusercontent.com/70543626/188988121-dad9daab-52f4-46c0-87ab-e63612e52fea.png)

@ctuanle này t nghĩ k sao mô 😅 đt nhỏ chịu thui, giảm text nhỏ quá thì k đọc đc chi cả

2022-09-08 08:49 UTC, Khanhtran47 approved these changes
![PandaCuteGIF](https://user-images.githubusercontent.com/54718468/189078763-b9b6eeec-9955-44c1-87bb-0d028a97ecf0.gif)

2022-09-08 09:01 UTC, merged