feature: anime search route #176
Khanhtran47/remix-movie pull request #182
Opened 2022-10-01 22:17 UTC by ctuanle

2022-10-01 22:28 UTC, ctuanle commented
@Khanhtran47  chỗ này sao đoạn search trang $animeKeyword nó k đc nhỉ, $movieKeyword đồ thì lại đc, k biết sai đoạn mô :v

2022-10-02 00:18 UTC, Khanhtran47 commented
> @Khanhtran47 chỗ này sao đoạn search trang $animeKeyword nó k đc nhỉ, $movieKeyword đồ thì lại đc, k biết sai đoạn mô :v

@ctuanle ừ lạ vại kiểu data nơi state nó vẫn chuyền xuống đều sao nó hiện thị bên ngoài vẫn cái cũ

2022-10-02 00:39 UTC, Khanhtran47 commented
@ctuanle m sửa như ri nơi file AnimeListGrid.tsx là ok, kiểu khi load data từ nơi server về phải setState lại data cũ load từ trc 

![image](https://user-images.githubusercontent.com/54718468/193433104-8a746ffe-3f38-4038-88e9-a85644930ec8.png)

2022-10-02 00:45 UTC, Khanhtran47 requested changes

2022-10-02 00:45 UTC, Khanhtran47 commented on app/routes/search/anime/$animeKeyword.tsx
> +            routeName="/anime/trending"
@ctuanle cái ni m sửa lại thành route đang search ý để nó fetch tiếp trang 2 của route nớ, k chi là nó fetch trang 2 của anime trending

2022-10-02 00:45 UTC, Khanhtran47 commented on app/routes/search/anime/$animeKeyword.tsx
> +            listName="Trending Anime"
@ctuanle cái ni hình như là search results

2022-10-02 00:45 UTC, Khanhtran47 commented on app/routes/search/anime/$animeKeyword.tsx
> +        textHelper={t('search.helper.tv')}
search.helper.anime

2022-10-02 00:45 UTC, Khanhtran47 commented on app/routes/search/anime/$animeKeyword.tsx
> +        textPlaceHolder={t('search.placeHolder.tv')}
search.placeHolder.anime

2022-10-02 00:45 UTC, Khanhtran47 commented on app/routes/search/anime/index.tsx
> +        textHelper={t('search.helper.tv')}
tv -> anime

2022-10-02 00:45 UTC, Khanhtran47 commented on app/routes/search/anime/index.tsx
> +        textPlaceHolder={t('search.placeHolder.anime')}
tv -> anime

2022-10-02 09:12 UTC, ctuanle commented on app/routes/search/anime/index.tsx
> +        textPlaceHolder={t('search.placeHolder.anime')}
@Khanhtran47  oulà, lộn tùm lùm :v

2022-10-02 10:37 UTC, Khanhtran47 approved these changes
còn update branch nữa rồi merge 

![ShiroAnimeGIF](https://user-images.githubusercontent.com/54718468/193449745-827f0ca3-5b3b-419b-b167-4f6d0f5c346a.gif)

2022-10-02 13:49 UTC, merged